version: '3.4'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 13579Maria
      MYSQL_DATABASE: OutofOffice
      MYSQL_USER: root
      MYSQL_PASSWORD: 13579Maria
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: OutofOfficeWebApp.Server/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      ConnectionStrings__OutofOfficeDBConnectionString: Server=db;Database=OutofOffice;User=root;Password=13579Maria;
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: outofofficewebapp.client/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  db_data:
